#!/bin/bash

# Set bash environment error management

set -e
set -u

# Source local functions file

source_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $source_dir/functions

# Check for root user runtime

check_root

################################################################################

# Download and source openspace functions file

download_os_functions
source_os_functions

################################################################################

os-define_formatting

define_vars

echo

################################################################################

if [[ "${@#--return-check}" = "$@" ]]
then
        echo "${r}${b}This script must not be run directly.${x}"
	echo
        echo "${b}You should instead run the | ${x}${g}${b}setup${x}${b} | script and it will take care of the installation itself.${x}"
	echo
        echo "${b}Exiting...${x}"
        echo
        exit 1
fi

################################################################################

os-check_install_version

################################################################################

echo "${b}Initiating installer...${x}"
echo

sed -i "/Subsystem/c\Subsystem sftp internal-sftp" "$ssh_config_file"

if ! grep -q "Match Group $sftp_group" "$ssh_config_file"
then
cat <<EOT >> "$ssh_config_file"

Match Group $sftp_group
    ChrootDirectory /home/%u
    ForceCommand internal-sftp
    PasswordAuthentication yes
    PermitTunnel no
    AllowAgentForwarding no
    AllowTcpForwarding no
    X11Forwarding no
EOT
fi

if ! grep -q $sftp_group /etc/group
then
        addgroup "$sftp_group"
fi

service ssh restart

rsync -aAXx $source_dir/ $install_dir/ --include=add-site-to-user --include=add-user --include=functions --exclude="*"

os-install_dependencies -p bindfs

echo "${b}Now removing installer directory...${x}"
echo
rm -r $source_dir
echo "${b}Finished removing installer directory.${x}"
echo

echo "${b}Installation complete!${x}"
echo
